name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  mongo_dart: ^0.9.1
  flutter_lints: ^3.0.0
  firebase_core: ^2.3.0
  cloud_firestore: ^4.1.0
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  mask_text_input_formatter: ^2.9.0
  flutter_masked_text2: ^0.9.1
  localstorage: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Projeto_integrador.Professor.json
    - assets/Projeto_integrador.Produtos.json
    - assets/Projeto_integrador.Aluno.json
    - assets/Projeto_integrador.Exercicios.json
    - assets/img/logo1.png
    - assets/img/quadrimusc.jpeg
    - assets/img/forearmmusc.jpg
    - assets/img/abdomemmusc.jpeg
    - assets/img/bracomusc.jpeg
    - assets/img/legmusc.jpeg
    - assets/img/tricepmusc.jpeg
    - assets/img/calf-muscle.jpg
    - assets/img/ombromusc.jpeg
    - assets/img/backmuscle.jpeg
    - assets/img/exercicio1.png
    - assets/img/exercicio2.png
    - assets/img/exercicio3.png
    - assets/img/exercicio4.png
    - assets/img/exercicio5.png
    - assets/img/exercicio6.png
    - assets/img/exercicio7.png
    - assets/img/exercicio8.png
    - assets/img/exercicio9.png